sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO=1.8
  - DJANGO=1.10

matrix:
  allow_failures:
    - env: COVERAGE=true

install:
  - pip install -U pip setuptools
  - pip install flake8
  - if [[ $DJANGO =~ = ]]; then
    pip install --pre --quiet "Django=$DJANGO";
    else
    pip install --quiet "Django>=$DJANGO,<$DJANGO.99";
    fi
  - make install

script:
  - make flake8
  - make test

after_script:
  - if [ "$COVERAGE" == "true" ]; then
    pip install --quiet python-coveralls;
    make coverage;
    coverage report;
    coveralls --ignore-errors;
    fi

notifications:
  email:
    - jacek@askesis.pl
